"""change name dodge to doge

Revision ID: 7f468812196d
Revises: 
Create Date: 2024-12-18 00:24:53.012708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f468812196d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doge', sa.Float(), nullable=True))
        batch_op.drop_column('dodge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dodge', sa.FLOAT(), nullable=True))
        batch_op.drop_column('doge')

    # ### end Alembic commands ###
